<?xml version="1.0" encoding="utf-8"?>
<graph>
  <vertices>
    <vertex ID="1" Performance="1" />
    <vertex ID="2" Performance="1" />
  </vertices>
  <edges>
    <edge Source="0" Target="1">
      <label Weight="1" />
    </edge>
  </edges>
  <layout>
    <position X="14.771281572659746" Y="99.243829123645355" />
    <position X="310.23546408965495" Y="98.134609707881808" />
  </layout>
</graph>